
# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
 
trigger:
- master
stages:
  - stage: build
    displayName: Build Application
    pool:
     name: 'MyUbuntuAgentPool'
    jobs:
      - job: build
        steps:
         - task: SonarQubePrepare@5
           inputs:
             SonarQube: 'sonarqube'
             scannerMode: 'Other'
         - task: SonarQubeAnalyze@5
           inputs:
             jdkversion: 'JAVA_HOME_11_X64'
