# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
 
stages:
  - stage: Build
    displayName: Build Application
    pool:
     name: 'MyUbuntuAgentPool'
    jobs:
      - job: Build
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          - task: SonarQubePrepare@5
            inputs:
              SonarQube: 'sonarqube'
              scannerMode: 'Other'
              extraProperties: |
                # Additional properties that will be passed to the scanner, 
                # Put one key=value per line, example:
                # sonar.exclusions=**/*.bin
                sonar.projectKey=sat_test
                sonar.projectName=sattest
          - task: SonarQubeAnalyze@5
            inputs:
               jdkversion: 'JAVA_HOME'
          - task: SonarQubePublish@5
            inputs:
              pollingTimeoutSec: '300'
            
              
          - task: CopyFiles@2
            inputs:
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: SonarQubePublish@5
            inputs:
              pollingTimeoutSec: '300'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: dev
    displayName: deploy to the develop environment
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        pool:
         name: 'MyUbuntuAgentPool'
        environment: dev
        strategy:
         runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'Free Trial (82fe0a7d-d99b-4167-a66d-d61381b992b9)'
                    appType: 'webAppLinux'
                    appName: 'test-app-dev'
                    package: '$(System.DefaultWorkingDirectory)/**/*.jar'
  - stage: QA
    displayName: deploy to the QA environment
    dependsOn: dev
    condition: succeeded()
    jobs:
      - deployment: Deploy
        pool:
         name: 'MyUbuntuAgentPool'
        environment: QA
        strategy:
         runOnce:
            deploy:
               steps:
                 - download: current
                   artifact: drop
                 - task: AzureWebApp@1
                   inputs:
                     azureSubscription: 'Free Trial (82fe0a7d-d99b-4167-a66d-d61381b992b9)'
                     appType: 'webAppLinux'
                     appName: 'test-app-qa'
                     package: '$(System.DefaultWorkingDirectory)/**/*.jar'
  - stage: staging
    displayName: deploy to the staging
    dependsOn: QA
    condition: succeeded()
    jobs:
      - deployment: Deploy
        pool:
         name: 'MyUbuntuAgentPool'
        environment: staging
        strategy:
         runOnce:
            deploy:
               steps:
                 - download: current
                   artifact: drop
                 - task: AzureWebApp@1
                   inputs:
                     azureSubscription: 'Free Trial (82fe0a7d-d99b-4167-a66d-d61381b992b9)'
                     appType: 'webAppLinux'
                     appName: 'test-app-stage'
                     package: '$(System.DefaultWorkingDirectory)/**/*.jar'
